version: '3.9'
name: d2a
services:
  alpine:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8022:22"
    container_name: test
    stdin_open: true # docker run -i
    tty: true        # docker run -t